CHROME_DRIVER_PATH = 'C:/dd/chromeDriverdd/chromedriver.exe'
CHROME_APP_PATH = 'C:/dd/Program Filesdd/Googledd/Chromedd/Applicationdd/chrome.exe'
CHROME_USER_DATA_DIR = 'C:/dd/Usersdd/utsavdd/OneDrivedd/Desktopdd/LinkedIn-Saral-Applydd/chromeDatadd/irangarick'
DEBUGGING_PORT = '9001'
DATABASE_URL = 'sqlite:///database.db'
