#!/bin/bash
#
# Saral Job Viewer — full stack deploy (Docker FastAPI backend + PM2 Vite frontend + nginx + SSL).
# Run from repo root: sudo ./deploy.sh
#
# Backend: Docker image from Dockerfile.api (app.py + utils/), listens on 8000 inside the container.
# Frontend: ./frontend via PM2 (vite preview behind nginx).
#
# Picks two free odd localhost ports. Default first candidate is SARAL_FIRST_ODD_PORT
# (37211) — high / uncommon vs typical dev & ad-hoc testing (3000, 5173, 8000, 8080,
# 3011, linkitup 3008/3009, etc.). Override: SARAL_FIRST_ODD_PORT, or set
# SARAL_BACKEND_PORT / SARAL_FRONTEND_PORT explicitly.

set -euo pipefail

GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

print_status() { echo -e "${GREEN}[INFO]${NC} $1"; }
print_header() { echo -e "${BLUE}$1${NC}"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }
print_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

DOMAIN="${SARAL_DOMAIN:-saral.thatinsaneguy.com}"
NGINX_TEMPLATE="$SCRIPT_DIR/nginx-saral.conf"
NGINX_STAGED="/tmp/nginx-saral.${DOMAIN}.conf"
NGINX_AVAILABLE="/etc/nginx/sites-available/${DOMAIN}"
NGINX_ENABLED="/etc/nginx/sites-enabled/${DOMAIN}"

# --- port helpers: prefer odd ports, avoid collisions ---
port_in_use() {
    local p="$1"
    if command -v ss >/dev/null 2>&1; then
        ss -tlnH 2>/dev/null | grep -qE ":${p}\b" && return 0
    fi
    if command -v netstat >/dev/null 2>&1; then
        netstat -tln 2>/dev/null | grep -qE ":${p}\s" && return 0
    fi
    return 1
}

next_free_odd_from() {
    local start="${1:-37211}"
    # ensure odd
    if (( start % 2 == 0 )); then start=$((start + 1)); fi
    local p="$start"
    while port_in_use "$p"; do
        p=$((p + 2))
        if (( p > 65533 )); then
            print_error "No free odd port found from $start"
            exit 1
        fi
    done
    echo "$p"
}

SARAL_FIRST_ODD_PORT="${SARAL_FIRST_ODD_PORT:-37211}"
BACKEND_PORT="${SARAL_BACKEND_PORT:-}"
FRONTEND_PORT="${SARAL_FRONTEND_PORT:-}"
if [[ -z "$BACKEND_PORT" ]]; then
    BACKEND_PORT="$(next_free_odd_from "$SARAL_FIRST_ODD_PORT")"
fi
if [[ -z "$FRONTEND_PORT" ]]; then
    # next odd after backend, still free
    FRONTEND_PORT="$(next_free_odd_from $((BACKEND_PORT + 2)))"
fi

if port_in_use "$BACKEND_PORT" || port_in_use "$FRONTEND_PORT"; then
    print_error "Ports not free: backend=$BACKEND_PORT frontend=$FRONTEND_PORT"
    exit 1
fi

print_header "🔢 Ports: host $BACKEND_PORT → API container :8000 | frontend PM2 $FRONTEND_PORT"

# --- Docker (backend) ---
if ! command -v docker &>/dev/null; then
    print_error "Docker is not installed. Install Docker and retry."
    exit 1
fi
if ! docker info >/dev/null 2>&1; then
    print_error "Docker daemon not reachable. Start Docker or add your user to the docker group."
    exit 1
fi

SARAL_API_IMAGE="${SARAL_API_IMAGE:-saral-job-viewer-api:latest}"
SARAL_API_CONTAINER="${SARAL_API_CONTAINER:-saral-job-viewer-api}"

print_header "🐳 Backend: build & run Docker ($SARAL_API_CONTAINER)..."
if [[ ! -f "$SCRIPT_DIR/Dockerfile.api" ]]; then
    print_error "Missing Dockerfile.api"
    exit 1
fi

docker build -f "$SCRIPT_DIR/Dockerfile.api" -t "$SARAL_API_IMAGE" "$SCRIPT_DIR"

docker rm -f "$SARAL_API_CONTAINER" >/dev/null 2>&1 || true

DOCKER_RUN=(docker run -d
    --name "$SARAL_API_CONTAINER"
    --restart unless-stopped
    -p "${BACKEND_PORT}:8000"
)
if [[ -f "$SCRIPT_DIR/.env" ]]; then
    DOCKER_RUN+=(--env-file "$SCRIPT_DIR/.env")
else
    print_warn "No .env in repo root — API needs MONGODB_URI etc. Pass envs or add .env before deploy."
fi
DOCKER_RUN+=("$SARAL_API_IMAGE")

"${DOCKER_RUN[@]}"

# --- PM2 (frontend only) ---
if ! command -v pm2 &>/dev/null; then
    print_error "PM2 is not installed. Install: npm install -g pm2"
    exit 1
fi

print_header "🧹 PM2 cleanup (saral-frontend; remove old saral-backend if any)..."
pm2 delete saral-backend >/dev/null 2>&1 || true
pm2 delete saral-frontend >/dev/null 2>&1 || true

FRONTEND_DIR="$SCRIPT_DIR/frontend"
if [[ ! -f "$FRONTEND_DIR/package.json" ]]; then
    print_error "frontend/package.json missing"
    exit 1
fi

print_header "📦 Frontend: npm install..."
cd "$FRONTEND_DIR"
npm install --silent 2>/dev/null || npm install

# Production: leave VITE_API_URL unset so requests use relative /api/...
export VITE_API_URL=""
print_header "🏗️  Frontend: npm run build..."
npm run build

cd "$SCRIPT_DIR"

ECOSYSTEM="$SCRIPT_DIR/ecosystem.saral.config.cjs"
ESC_FE="${FRONTEND_DIR//\\/\\\\}"

cat >"$ECOSYSTEM" <<EOF
/** Generated by deploy.sh — frontend only; API runs in Docker */
module.exports = {
  apps: [
    {
      name: "saral-frontend",
      cwd: "${ESC_FE}",
      script: "npm",
      args: "run preview -- --host 0.0.0.0 --port ${FRONTEND_PORT}",
      interpreter: "none",
      instances: 1,
      autorestart: true,
      max_restarts: 20,
      min_uptime: "5s",
    },
  ],
};
EOF

print_header "🚀 PM2: starting saral-frontend..."
pm2 start "$ECOSYSTEM"
pm2 save >/dev/null 2>&1 || true

# --- nginx from template ---
echo ""
print_header "🌐 Nginx ($DOMAIN)"

if [[ ! -f "$NGINX_TEMPLATE" ]]; then
    print_error "Missing $NGINX_TEMPLATE"
    exit 1
fi

sed -e "s/__BACKEND_PORT__/${BACKEND_PORT}/g" -e "s/__FRONTEND_PORT__/${FRONTEND_PORT}/g" \
    "$NGINX_TEMPLATE" >"$NGINX_STAGED"

if ! command -v nginx &>/dev/null; then
    print_warn "nginx not installed. PM2 apps are running; configure nginx manually:"
    echo "  sudo cp $NGINX_STAGED $NGINX_AVAILABLE"
    echo "  sudo ln -sf $NGINX_AVAILABLE $NGINX_ENABLED"
    echo "  sudo nginx -t && sudo systemctl reload nginx"
    echo "  printf '\\nA\\n1\\n' | sudo certbot --nginx -d $DOMAIN"
else
    if [[ "$EUID" -ne 0 ]] && [[ -z "${SUDO_USER:-}" ]]; then
        print_warn "Not root — copy nginx config manually:"
        echo "  sudo cp $NGINX_STAGED $NGINX_AVAILABLE"
        echo "  sudo ln -sf $NGINX_AVAILABLE $NGINX_ENABLED"
        echo "  sudo rm -f /etc/nginx/sites-enabled/default"
        echo "  sudo nginx -t && sudo systemctl reload nginx"
        echo "  printf '\\nA\\n1\\n' | sudo certbot --nginx -d $DOMAIN"
    else
        print_status "Installing nginx site..."
        cp "$NGINX_STAGED" "$NGINX_AVAILABLE"
        ln -sf "$NGINX_AVAILABLE" "$NGINX_ENABLED"
        rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true

        print_status "nginx -t"
        if nginx -t >/dev/null 2>&1; then
            systemctl reload nginx >/dev/null 2>&1 || service nginx reload >/dev/null 2>&1 || true
            print_status "nginx reloaded"
        else
            print_error "nginx -t failed — fix config at $NGINX_AVAILABLE"
            exit 1
        fi

        echo ""
        print_header "🔒 SSL (certbot)"
        if ! command -v certbot &>/dev/null; then
            print_warn "certbot missing; install (e.g. apt install certbot python3-certbot-nginx) then:"
            echo "  printf '\\nA\\n1\\n' | sudo certbot --nginx -d $DOMAIN"
        else
            CERTBOT_EMAIL_ARGS=()
            if [[ -n "${SARAL_CERTBOT_EMAIL:-}" ]]; then
                CERTBOT_EMAIL_ARGS=(--email "$SARAL_CERTBOT_EMAIL")
            fi
            if certbot --nginx -d "${DOMAIN}" --non-interactive --agree-tos --keep-until-expiring "${CERTBOT_EMAIL_ARGS[@]}" 2>/dev/null; then
                print_status "SSL OK (non-interactive)"
            else
                print_status "Trying certbot with piped prompts..."
                printf '\nA\n1\n' | certbot --nginx -d "${DOMAIN}" 2>/dev/null || \
                    print_warn "certbot may need manual run for $DOMAIN"
            fi
            nginx -t >/dev/null 2>&1 && (systemctl reload nginx >/dev/null 2>&1 || service nginx reload >/dev/null 2>&1 || true)
        fi
    fi
fi

# Persist chosen ports for operators
PORTS_FILE="$SCRIPT_DIR/.deploy-ports.env"
umask 077
cat >"$PORTS_FILE" <<EOF
# Written by deploy.sh — source or re-export for debugging
SARAL_DOMAIN=$DOMAIN
SARAL_FIRST_ODD_PORT=$SARAL_FIRST_ODD_PORT
SARAL_BACKEND_PORT=$BACKEND_PORT
SARAL_FRONTEND_PORT=$FRONTEND_PORT
EOF
chmod 600 "$PORTS_FILE" 2>/dev/null || true

echo ""
print_header "✅ Deploy finished"
print_status "Local:  http://127.0.0.1:${FRONTEND_PORT} (UI)  http://127.0.0.1:${BACKEND_PORT}/api/health (API via Docker)"
print_status "Public: https://${DOMAIN}/  and  https://${DOMAIN}/api/"
print_status "Ports saved: $PORTS_FILE"
print_status "pm2 status | pm2 logs saral-frontend"
print_status "docker ps | docker logs -f ${SARAL_API_CONTAINER}"
