/** Generated by deploy.sh — frontend only; API runs in Docker */
module.exports = {
  apps: [
    {
      name: "saral-frontend",
      cwd: "/home/uttu28/Desktop/Saral-Job-Viewer/frontend",
      script: "npm",
      args: "run preview -- --host 0.0.0.0 --port 8005",
      interpreter: "none",
      instances: 1,
      autorestart: true,
      max_restarts: 20,
      min_uptime: "5s",
    },
  ],
};
